eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://microserviceeureka-env.eba-mnhqfsqq.us-east-2.elasticbeanstalk.com/eureka/
      defaultZone: http://localhost:8761/eureka/
